### PR TITLE
Reapplied #134 with additional checks to tackle unintentional scrolls

### PR DESCRIPTION
**Pull request by stammbach**
I've also had problems with the #134 fix just like #210, on a very long form page the view would scroll to the top every time a user closes the keyboard (also happens when the user clicks a checkbox) which is not very user friendly.

Im currently calculating the maximum content offset / viewport, and only scroll to **that** maximum if the current offset is overlapping it. On my current project it seems to work perfectly.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Looks really good to me. Need someone to test & verify that it works, but otherwise 👍 .

**Comment by stammbach** [comment]
Hey @jamonholmgren, I've updated the keyboardDisplacementFix method to catch some edge cases where the contentSize of the scrollView might be smaller than the frame, just to be safe.

**Comment by stammbach** [comment]
Maybe one of you guys can help us with testing this 🙏@iamtommcc @malonguwa

**Comment by Titozzz** [comment]
@ryanlntn You were the one requesting #210, can you test this one to make sure it's not breaking anymore?

**Comment by Titozzz** [comment]
Tested and approved on my app ✅ , going to merge this now

**Comment by ryanlntn** [comment]
Apologies for the belated response, been in the middle of a big launch prep. I can confirm that this is working for me as well! 😄

**Pull request merged**
