### PR TITLE
Add 'allowsBackForwardNavigationGestures' property to the iOS WKWebview

### PR DESCRIPTION
**Pull request by bae-unidev**
Fixes [issue](https://github.com/facebook/react-native/issues/21336) for the WKWebView.

1. Add 'allowsBackForwardNavigationGestures' property to the iOS WKWebview

### CODE REVIEW

**Comment by Titozzz** [comment]
Ouch I did break cocoapods when setting up semantic release then :( . Can you split your PR for more visibility ? I'll merge ASAP

**Comment by Titozzz** [comment]
Hello, I updated master so that semantic release is now publish the version to package.json. Were you using a git url to pull the code by the way instead of npm registry ? Else I don't understand how you got that bug 🤔

**Comment by bae-unidev** [comment]
I needed this feature so I was using forked git url. If this commit merged and package is published, we will fix it and you can ignore that errors.

**Comment by Titozzz** [comment]
Okay this is why you had no version inside package.json. It makes sense now :)

**Pull request merged**
