### PR TITLE
fix: support original view props, such as onLayout

### PR DESCRIPTION
**Pull request by CubeSugar**
`WebView` should have the `View`'s generic props, such as `onLayout`, according to the [doc](https://facebook.github.io/react-native/docs/webview#props).

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@CubeSugar Thanks for submitting this! Without painstakingly going through and checking every prop, is there a way to check to make sure you didn't mistakenly remove some?

**Comment by CubeSugar** [comment]
@jamonholmgren  I modified these lines carefully. It works in my own case. 

But, to be honest, I do not figure out a elegant way to show whether I mistakenly remove some props.

All props are unpacked by `{...this.props}`. And the wrapped props, such as `onMessage`, are marked and shown in the pictures below. 

May u have a glance? 😄 

ios

android

**Comment by jamonholmgren** [comment]
This is where #171 would be very helpful. 😁

**Comment by CubeSugar** [comment]
@jamonholmgren

OK, I'll work on it ASAP. :)

**Comment by CubeSugar** [comment]
@jamonholmgren

I checked the lines carefully and resolved the conflict by removing redundant props.

**Comment by jamonholmgren** [comment]
@CubeSugar Would you mind resolving conflicts? Thanks for your patience!

**Comment by CubeSugar** [comment]
@jamonholmgren Conflicts resolved. 👌

**Comment by Titozzz** [comment]
I'll go over the props one by one asap since this was opened a long time ago.

**Comment by Titozzz** [comment]
Actually the typescript rewrite took care of this PR

**Comment by Titozzz** [comment]
Because of the TS rewrite, I directly included this in my PR so you don't fight against merge conflicts

**Comment by jamonholmgren** [comment]
Thanks @Titozzz and to @CubeSugar for your original work on this!

**Pull request closed without merging**
