### PR TITLE
add allowFileAccessFromFileURLs propery to do the expected on android

### PR DESCRIPTION
**Pull request by bobalazek**
# Summary

Render a local HTML file (referencing assets in the same folder) is not possible on Android. For this to be possible allowFileAccessFromFileURLs has to be set to true.

This PR adds this prop to the underlying WebView.

> **Not my work/PR - it's just https://github.com/react-native-community/react-native-webview/pull/695 with the fixed branch. Need the functionality for a project I'm just working on.**

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

### CODE REVIEW

**Comment by bobalazek** [comment]
Is there any issue?

**Comment by Titozzz** [comment]
Hello, was super busy at RNEu last week, can you please at types to this PR as said in the previous one 😄 ?

**Comment by bobalazek** [comment]
There we go!

**Comment by bobalazek** [comment]
Anything else?

**Comment by hsource** [comment]
This is great! One additional change that's needed - the Typescript types needs to add the parameter to the `interface AndroidWebViewProps` as well as the native props you've added it to.

Feel free to copy from this additional commit:
https://github.com/hsource/react-native-webview/commit/d4d32c12a5ff7507ee3396430a541d66a7bd8049

**Comment by bobalazek** [comment]
Added now.

**Pull request merged**
