### PR TITLE
Update lock file

### PR DESCRIPTION
**Pull request by safaiyeh**
# Summary
GitHub actions test are breaking due to an outdated lock file. Updated to fix CI/CD on master.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by mohsinulhaq** [comment]
Hi, just wanted to understand as to why you guys do releases even on lockfile changes.

**Comment by safaiyeh** [comment]
@mohsinulhaq this one was necessary for windows support.

**Comment by mohsinulhaq** [comment]
@safaiyeh do you mean development on windows?

**Comment by safaiyeh** [comment]
@mohsinulhaq React Native for Windows Desktop

**Comment by mohsinulhaq** [comment]
yeah, since `react-native-windows` is a dev dependency, I believe your change is only going to affect development, since package lock is not a part of published package.

**Pull request merged**
