### PR TITLE
fix(gradle): Add support library as a dependency

### LINKED ISSUE #174: android build failed with task :react-native-webview:compileDebugJavaWithJavac
what I have done:

```
$ yarn add react-native-webview
$ react-native link react-native-webview
```

In android-studio after sync then I make project  failed:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
```

- I have cleaned project
- I have removed ~/.gradle/caches
- I have removed project .gradle folder

```
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
```

### LINKED ISSUE #184: Android Studio cannot find symbol class RNCWebViewPackage
I tried @FaiChou's fix to comment out RequireAPI, but am still receiving errors building with this package not being found by Android Studio even though it appears to be properly linked and exists within node_modules.

settings.gradle contains:
`include ':react-native-webview'
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')`

MainApplication.java contains:
`import com.reactnativecommunity.webview.RNCWebViewPackage;`

`npm 6.4.1
react-native 0.57.7
node 10.13.0`

am I missing something?

### LINKED ISSUE #245: Android Support Annotation library not included in projects build.gradle
This is an issue because now every developer has to manually update this library's build.gradle file to include the "support-annotations" dependency. 

This seems to be the only way to fix this issue.

Changing my import back to 
**import {WebView} from 'react-native';** pending when this issue is resolved.

### PR DESCRIPTION
**Pull request by Titozzz**
fixes #174 
fixes #184 
fixes #245

### CODE REVIEW

**Comment by Titozzz** [comment]
@FaiChou @capitalistdog @MaheshNandam @AE0011 @swansontec @Lizhooh @nonotest @iv47 @zeekay18 Can you please verify this PR solves your issues so that I can merge ASAP ?

Thanks ❤️

**Comment by Titozzz** [comment]
@all-contributors please add titozzz for code, ideas, review, maintenance, testing, doc, infra

**Comment by swansontec** [comment]
@Titozzz Just tested v3.1.3, and it works right out of the box with no build errors on either Android or iOS. Many thanks 🙏!

**Pull request merged**
