### PR TITLE
Add 'userAgent' property to the iOS WKWebView.

### PR DESCRIPTION
**Pull request by bae-unidev**
Add 'userAgent' property to the iOS WKWebView. 

The property to set the userAgent in the iOS WKWebview is [customUserAgent](https://developer.apple.com/documentation/webkit/wkwebview/1414950-customuseragent). But to make the interface the same, I set userAgent props to WKWebview customUserAgent.

### CODE REVIEW

**Comment by KoenLav** [comment]
@Titozzz aren't you vouching for removing UIWebView completely soon?

**Comment by bae-unidev** [comment]
@Titozzz 

UIWebview does not officially change the `User-Agent`. Instead, there are three hacks:

- Modify window.navigator.userAgent in the js context with the stringByEvaluatingJavaScriptFromString API.
- Replace the `User-Agent` Header for all requests in the `loadRequest`.
- Modify `NSUserDefaults` to override the settings for the entire app.

Mostly not modern, just HACK. It seems good to add that docs do not support it, is that what you think?

**Comment by johanforssell** [comment]
What about this text in `Reference.md`:
```
### `userAgent`

Sets the user-agent for the `WebView`. This will only work for iOS if you are using WKWebView (see https://developer.apple.com/documentation/webkit/wkwebview/1414950-customuseragent), not UIWebView.

| Type   | Required |
| ------ | -------- |
| string | No       |
```

**Comment by Titozzz** [comment]
@KoenLav You are right, I'll remove it soon, too tired to keep maintaining it.

But I the meantime I like to keep everything clean and up to date ^^'

**Comment by xclidongbo** [comment]
I want to get useragent in wkwebview. How can I do it?

**Pull request merged**
