### PR TITLE
fix(android): Allow scrolling inside ScrollView

### PR DESCRIPTION
**Pull request by masako-yamada**
Try fixing #22 
This should work in general, however, there would be some edge cases where it doesn't work.
Hope others improve this.

### CODE REVIEW

**Comment by MarkIgnaczakBB** [comment]
This seems to indeed fix this issue: https://github.com/react-native-community/react-native-webview/issues/22.

WebView now correctly scrolls and follows user's move gesture (e.g. such as if an image zooms in by user hovering their finger around).

**Comment by vvusts** [comment]
I just tried this PR fixed webview scrolling when webview is inside scroll view.

**Comment by N-Milinkovic** [comment]
@masako-yamada This has conflicts, but also doesn't have anyone set as reviewers, maybe need to add them to get their attention?

**Comment by masako-yamada** [comment]
I fixed the conflict, @N-Milinkovic or somebody, would you check if this works?
I couldn't test it by myself since the latest master requires androidx (NN >= 60) and my project has not migrated to it. :-(

**Comment by N-Milinkovic** [comment]
> I fixed the conflict, @N-Milinkovic or somebody, would you check if this works?
> I couldn't test it by myself since the latest master requires androidx (RN >= 60) and my project has not migrated to it. :-(

I have tested in a RN >= 60 project and it works just need approval from one of the reviewers

**Comment by gasolin** [comment]
@jamonholmgren / @Titozzz the conflict is fixed, would you mind to review this PR?

**Comment by brentvatne** [comment]
can you explain your PR in more detail?

i'm not sure this is desirable, my understanding is that it always makes the webview scrollable when inside of a scrollview. you could use react-native-gesture-handler to coordinate this instead - wrap the WebView in `NativeViewGestureHandler` and set a ref on it, then use the `ScrollView` imported from rngh and use the `waitFor` prop

**Comment by jamonholmgren** [comment]
@brentvatne Can you provide an example code snippet that shows that approach in action?

**Comment by brentvatne** [comment]
@jamonholmgren - can't repro the original issue from the code snippet posted in #22 op, any tips? https://snack.expo.io/@notbrent/authentic-watermelon

**Comment by gasolin** [comment]
I use the example https://snack.expo.io/r1E6viX0N to test with snack version, the horizontal scroll is still sluggish on Android

**Comment by brentvatne** [comment]
gotcha, here's a repro: https://snack.expo.io/@notbrent/insane-almond

couldn't get it working with RNGH so a solution may indeed be needed on the webview itself

**Comment by Titozzz** [comment]
let's ship it, but I'll be monitoring issues to make sure no one is complaining about that change

**Comment by brentvatne** [comment]
@Titozzz - maybe it makes sense to put the behavior behind a prop so it's easy for people to enable, then make it default in a major version bump?

**Comment by wsliaw** [comment]
@Titozzz, agree with @brentvatne, make it a prop seems more reasonable

**Comment by Titozzz** [comment]
It was causing too many issues for people (see #878) so I reverted it. Feel free to submit a new PR 😄

**Comment by Titozzz** [comment]
The thing with a prop is that it's encouraging keep 2 half working versions instead of finding something that'll fix for everyone 😢

**Comment by kefyru** [comment]
COOL!!!!

**Comment by jordangrant** [comment]
Applied this PR manually, exactly what I needed, thanks

**Pull request merged**
