### PR TITLE
Add mainDocumentURL to onShouldStartLoadWithRequest for iOS

### PR DESCRIPTION
**Pull request by pmusaraj**
When using `onShouldStartLoadWithRequest` to intercept external links and launch Safari for them, I ran into an issue. AJAX requests (like Google Ads) were sometimes triggering `onShouldStartLoadWithRequest` and since these could be external, the interceptor was launching those requests. 

This PR exposes `request.mainDocumentURL`, which I used to avoid the scenario described above.

### CODE REVIEW

**Comment by vivan-niche** [comment]
related/similar to https://github.com/react-native-community/react-native-webview/pull/163

**Comment by Titozzz** [comment]
Please update types

**Comment by pmusaraj** [comment]
I'm sorry, I don't understand what "update types" means. I have merged master into this branch, did you mean that?

**Comment by Titozzz** [comment]
Don't apologise I should have been more clear. Please also edit the typescript types so that it reflects your changes

**Comment by pmusaraj** [comment]
Thanks @Titozzz, types now updated.

**Comment by Titozzz** [comment]
since it's only on iOS, you should add the property as optional or create 2 separate types :)

**Comment by Strate** [comment]
Hi, would you please release it under v5 branch?

**Pull request merged**
