### PR TITLE
fix inconsistent backgroundColor

### PR DESCRIPTION
**Pull request by wsliaw**
# Summary

Fix inconsistent background color when loading html & html loaded.
I implement this by setting background color right after webview init.

## Test Plan

1.
```
<Webview source={html:'<html></html>'} style={{backgroundColor:'transparent'}} />
```
we can see background color is always transparent (before applying this fix it will show a white background when loding)

2.
```
<Webview source={html:'<html></html>'} style={{backgroundColor:'white'}} />
```
set backgroundColor to white or without setting any backgroundColor, the result will be totally the same as current version, which is white.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by Titozzz** [comment]
Shouldn't we remove setBackgroundColor from other places if we add it here as it might be redundant?

**Comment by wsliaw** [comment]
> Shouldn't we remove setBackgroundColor from other places if we add it here as it might be redundant?

Agree, removed redundant setBackgroundColor and tested on both device & simulator

**Comment by brandons** [comment]
This fixes the white background issue mentioned here. https://github.com/react-native-community/react-native-webview/pull/587 @Titozzz

**Comment by kefyru** [comment]
how it works? I use <WebView style={{backgroundColor='transparent'.... or any other, but it still white...
in WebView@7.2.3
rn 0.60.5

**Comment by liquidvisual** [comment]
Yeah, this doesn't work.

**Pull request merged**
