### PR TITLE
Add postMessage for Windows WebView

### PR DESCRIPTION
**Pull request by kaiguo**
# Summary
Added postMessage function.

### CODE REVIEW

**Comment by safaiyeh** [comment]
Hi @kaiguo could you make sure to update the docs with this new addition

**Comment by kaiguo** [comment]
> Hi @kaiguo Kai Guo FTE could you make sure to update the docs with this new addition

@safaiyeh updated : )

**Comment by jamonholmgren** [comment]
@kaiguo Would you mind fixing conflicts? I started to but I think it needs your eyes on it.

**Comment by kaiguo** [comment]
@jamonholmgren I just resolved the conflicts, could you help get this in when you get a chance? Thanks!

**Pull request merged**
