### PR TITLE
[Windows] Fix issue where WebView events could not be send when multiple WebView in the application

### PR DESCRIPTION
**Pull request by tero-paananen**
## Summary

When application has more than one WebView causes that WebView's event are not anymore sent (for example `WebView.NavigationCompleted()`) See more about issue [#1572](https://github.com/react-native-community/react-native-webview/issues/1572)

Bug is that `ReactWebViewManager` deletes always previous WebView instanse in method:
```
 winrt::FrameworkElement ReactWebViewManager::CreateView() noexcept {
        m_reactWebView = *winrt::make_self<ReactWebView>(m_reactContext);
        return m_reactWebView.GetView();
    }
```

Fix is to give whole `ReactWebView` that is `UserControl` and contains `WebView` as content and there is no need to store ReactWebView` instance as variable in `ReactWebViewManager`. Next `CreateView` call does not anymore reset pointer of previous `ReactWebView`. 
```
winrt::FrameworkElement ReactWebViewManager::CreateView() noexcept {
      auto view = winrt::ReactNativeWebView::ReactWebView(m_reactContext);
      return view;
    }
```

## Test Plan

See example app from the  issue [#1572](https://github.com/react-native-community/react-native-webview/issues/1572) and see how events are missing.

## Compatibility

Windows 10
"react-native": "0.62.2"
"react-native-windows": "0.62.5"

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`

### CODE REVIEW

**Comment by tero-paananen** [comment]
This PR closes #1572

**Comment by tero-paananen** [comment]
See PR https://github.com/react-native-community/react-native-webview/pull/1617 that icludes these fixes also

**Comment by luojiong** [comment]
I also encountered this problem. Can I merge it?  @jamonholmgren

**Comment by tero-paananen** [comment]
Do not merge this invalid PR, see my new PR https://github.com/react-native-community/react-native-webview/pull/1617

**Comment by luojiong** [comment]
thank you

**Pull request closed without merging**
