### PR TITLE
feat(android): add clearHistory, clearCache and clearFormData

### PR DESCRIPTION
**Pull request by punksta**
https://github.com/react-native-community/react-native-webview/issues/380

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@punksta Thanks for contributing this! Could you update documentation too, while you're at it?

**Comment by punksta** [comment]
@jamonholmgren done

**Comment by punksta** [comment]
@jamonholmgren could you also recheck this https://github.com/react-native-community/react-native-webview/pull/451 ? it's sort of stuck

**Comment by Titozzz** [comment]
please udpate types, as theses methods should be on android only, you can create AndroidWebViewCommands extending from WebViewCommands

**Comment by Titozzz** [comment]
I'm still okay with merging this if it's fixed

**Comment by punksta** [comment]
great! I still want to get this merged, will try to find time this week.

**Comment by punksta** [comment]
@Titozzz hello :) I finally found time

**Comment by punksta** [comment]
@Titozzz thanks for waiting and reviewing.

**Pull request merged**
