### PR TITLE
add-javaScriptEnabled-in-IOS

### PR DESCRIPTION
**Pull request by aksmfosef11**
# Summary
When opening Google Docs in the IOS WebView
If `JavaScriptEnabled` is true, Google Docs will have a header.
There is also a page called Clear the cache and the cookies.

I fixed this problem by adding `javaScriptEnabled` to IOS.

One `javaScriptEnabled` variable and five lines of code have been added.

I used javaScriptEnabled in `WKPreferences`.

In addition to the issues I mentioned, you can solve problems that occur when iOS can not use `javaScriptEnabled` as false.

## Test Plan

Just add 5 lines to RNCWKWebView.m.

```
WKPreferences * prefs = [[WKPreferences alloc] init];
     if (! _ javascriptEnabled) {
       prefs.javaScriptEnabled = NO;
       wkWebViewConfig.preferences = prefs;
     }
```

The simplest test is to open Google Docs with WebView in IOS.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [X] I have tested this on a device and a simulator
- [x] I updated the typed files (TS and Flow)

### CODE REVIEW

**Comment by Titozzz** [comment]
Please update types also :)

**Comment by aksmfosef11** [comment]
@Titozzz 
How do I update types?
Is it correct to edit the` WebView.ios.tsx` file?

**Comment by Titozzz** [comment]
Moved types from android to shared

**Comment by mars-lan** [comment]
For whatever reason this broke loading Instagram mobile site in WebView. It's stuck in the initial loading screen.

Screen Shot 2019-08-29 at 7 37 37 PM

**Pull request merged**
