### PR TITLE
Fix iOS(WKWebView cannot trigger “onNavigationStateChange” when chang…

### PR DESCRIPTION
**Pull request by shanchaojie**
…ing url)。

# Summary

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by tianweicc** [comment]
the  question  Still exist

**Comment by shanchaojie** [comment]
> the question Still exist
 I've tested it is no problem. Can you give me the URL you tested?

**Comment by xxf1110** [comment]
the question Still exist

**Comment by shanchaojie** [comment]
> the question Still exist

Can you give me the URL? I test some URLs are fine.

**Comment by xxf1110** [comment]
hash change, ios canGoBack return false

**Pull request closed without merging**
