### PR TITLE
Add "Frame load interrupted" error handling for OAuth for RNCWKWebView

### PR DESCRIPTION
**Pull request by oNaiPs**
Adds the same code that is on `RNCUIWebview` https://github.com/react-native-community/react-native-webview/blob/master/ios/RNCUIWebView.m#L271 for the same purpose.

I came across this problem while implementing google SAML support with the RNCWKWebView.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Thanks for the PR @oNaiPs ! How would I go about testing this?

**Comment by oNaiPs** [comment]
> Thanks for the PR @oNaiPs ! How would I go about testing this?

@jamonholmgren not sure, I came across this error while developing with google SAML for an internal service.

**Comment by tigo0** [comment]
This works in our case with the authentication flow. Thanks

**Comment by Titozzz** [comment]
Thank @tigo0 for testing this, I'll merge into master

**Pull request merged**
