### PR TITLE
Allow custom CA to be used on webview requests

### PR DESCRIPTION
**Pull request by eaceto**
# Summary

This commit allows us to use custom Certificate Authorities (aka self-signed certificates) with WebView without disabling SSL check.
It's also valid for those wanting to implement SSL Pinning over the WebView requests.

I implemented this by modifying webView:didReceiveAuthenticationChallenge:completionHandler in order to look into a Map of hosts/Certificates for the right certificate. If we have the same certificate the server presents, then it's a trusted cert. 

This features impacts only on RNCWebView.

## Test Plan

Create a self-signed certificate and assign it to a website. 
Then in your iOS App copy the DER file of the certificate into the bundle, load it and set it in your AppDelegate. For example:

```
  NSBundle *bundle = [NSBundle mainBundle];
  NSMutableDictionary* certMap = [NSMutableDictionary new];

  // Get Certificate from Bundle file
  {
    NSData *rootCertData = [NSData dataWithContentsOfFile:[bundle pathForResource:@"example.com" ofType:@"der"]];
    SecCertificateRef certificate = SecCertificateCreateWithData(NULL, (CFDataRef) rootCertData);
    OSStatus err = SecItemAdd((CFDictionaryRef) [NSDictionary dictionaryWithObjectsAndKeys:(id) kSecClassCertificate, kSecClass, certificate, kSecValueRef, nil], NULL);
    [certMap setObject:(__bridge id _Nonnull)(certificate) forKey:@"example.com"];
  }
 
  // Set a Map of hosts / certificates
  [RNCWebView setCustomCertificatesForHost:certMap];
```
### What's required for testing (prerequisites)?

* Having a SelfSigned Certificate

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by dulmandakh** [comment]
@eaceto could you please revert back spacing changes, it would improve readability and makes review easy.

**Comment by eaceto** [comment]
Hello @dulmandakh 

I made the requested changed.

**Comment by Titozzz** [comment]
Would this potentially be a breaking change?

**Comment by eaceto** [comment]
Not at all. This change introduces a new (optional) feature. It doesn’t break the existing API, and introduces a new method that may be called from the AppDelegate in case it’s needed. 
Most apps don’t implement SSL Pinning, but this is a security standard in enterprises.

**Comment by eaceto** [comment]
I will submit a PR for the Readme ASAP.
Thanks

**Comment by samitha9125** [comment]
@Titozzz @eaceto 

Recently I faced an issue with Microsoft login where using Charles and custom certificate, can extract username and the password without any problem by monitoring the traffic even through it used HTTPS. So I'm curious to know, after using this method in iOS, can we stop such sensitive data exposure using SSL Pinning?  Also love to see updated doc soon. Great work guys.

**Comment by eaceto** [comment]
Hello @samitha9125 , excuse me for the delaying in replaying, I was on vacations.
Using SSL Pinning, the custom SSL certificate that Chales Proxy exposes to your (react native) app will be rejected by the app. Leading in not loading the login page.
I'm curious how you implemented the Microsoft Login as it should only work using HTTPS and a valid certificate.

**Comment by flexaddicted** [comment]
@eaceto I'm wondering why you use `SecItemAdd` in this example.

Thanks, Lorenzo

**Comment by eaceto** [comment]
Hello @flexaddicted. In this example is not needed, I just extracted it from a more complex example where then the certificate was used (from the KeyChain). Sorry for that, hope it didn't produce you a problem.

**Comment by flexaddicted** [comment]
@eaceto not at all but it should be removed since unnecessary.

**Comment by eaceto** [comment]
I commented it out in the example. Thanks!!!

**Comment by romixch** [comment]
I wonder why the hostname is used as key here. Now I have to know all the hosts which use my custom certificate authority in advance. Wouldn't it be easier to have a list of trusted authorities and test against those? Just the way a browser does.

**Comment by theMasix** [comment]
Hi @eaceto . Thanks for the immediate response after my previous comment. Any good news?

**Comment by hpelitebook745G2** [comment]
any updates on this @eaceto ? appreciate your time and response.

**Comment by eaceto** [comment]
Hello! I thought about implementing a solution similar to the iOS one, with a fine-grained control, but I found it not useful when you can use Android Network Security Config for the same purpose.

https://developer.android.com/training/articles/security-config

You can add trusted CAs to your app, and perform SSL pinning easily by describing a XML like this:

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config>
        <domain includeSubdomains="true">secure.example.com</domain>
        <domain includeSubdomains="true">cdn.example.com</domain>
        <trust-anchors>
            <certificates src="@raw/trusted_roots"/>
        </trust-anchors>
    </domain-config>
</network-security-config>

In contrast, iOS does not provide built-in SSL Pinning, but Android does.

**Pull request merged**
