### PR TITLE
Fixing typing.

### PR DESCRIPTION
**Pull request by bruteforcecat**
so happy to see there is typing in the newest release.
I added back WebViewIOSLoadRequestEvent which also exist in react-native typing and fix startInLoadingState which should be boolean.

### CODE REVIEW

**Comment by Titozzz** [comment]
@bruteforcecat Are you willing to convert all to TS ?

**Comment by bruteforcecat** [comment]
I think I could do this. so no more flow-typed? but you want to change the setup as well?

**Comment by Titozzz** [comment]
Yeah we will remove flow. Ideally we can generate flow types from TS and export them if people need them

**Comment by Titozzz** [comment]
#168

**Pull request merged**
