### PR TITLE
Add incognito prop to iOS WKWebview

### PR DESCRIPTION
**Pull request by oNaiPs**
Allows the webview to be opened with an ephemeral data storage.

Looks like there is no out-of-the-box support for `UIWebView` so I didn't implement that.
I think there should be a relatively simple way to implement this on Android as well.

### CODE REVIEW

**Comment by Andreyco** [comment]
FYI, using this fork in production app, works well!

**Comment by Titozzz** [comment]
@Andreyco Thanks for your testing, I'll merge this

**Comment by Andreyco** [comment]
Superb!

**Pull request merged**
