### PR TITLE
Android webrtc permission request - conflicts fixed

### PR DESCRIPTION
**Pull request by eactisgrosso**
Hello @Titozzz, I fixed the conflicts and tested it successfully in simulator and device:

Screenshot_1562993409

Screenshot_2019-07-12-18-21-02

Let me know if there's anything else I can do to help move @Javascript-Ninja's fix forward.
Thanks!

### CODE REVIEW

**Comment by malpower** [comment]
hi guys,
this looks very useful, nice idea.
i just wanna know when can this feature be released?

**Comment by Titozzz** [comment]
There is so many unnecessary changes due to you code formatter, can you please remove those?

**Comment by eactisgrosso** [comment]
Let me try to find time today to do it.

**Comment by moh3n9595** [comment]
what about location permission?

**Pull request merged**
