### PR TITLE
Implementing minimumFontSize for Android

### PR DESCRIPTION
**Pull request by tmaly1980**
# Summary

Android WebView enforces a default minimum font size of 8 (see https://developer.android.com/reference/android/webkit/WebSettings#setMinimumFontSize(int)), causing scaling issues when using smaller font sizes. Content that may be deliberately scaled down to fit 100% width of the device may overflow. This property allows for customizing the minimum font size so scaling appears similar as on iOS. 

In cases where grids of content/text are displayed (such as a seating chart), font size may need to be scaled down to fit the entire grid onto one screen width.

### What's required for testing (prerequisites)?

Running on Android.

### What are the steps to reproduce (after prerequisites)?

Reference HTML code that uses font sizes < 8. For example:

`
<WebView source={{ html: '<html><body><span style="font-size: 4px;">Font size 4</span></body></html>' }} minimumFontSize={1} />
`

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `Reference.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by Titozzz** [comment]
Please add types, but everything else looks good :)

**Comment by tmaly1980** [comment]
@Titozzz Can you clarify what you mean? I'm just coding it in the style like everything else is coded, I don't see that I'm missing anything semantically.

**Comment by jamonholmgren** [comment]
@tmaly1980 You would need to add the type to the TypeScript interface, somewhere around here:

https://github.com/react-native-community/react-native-webview/blob/5ddd6c6fc277b348d1e6725c76f98ab55ea282c1/src/WebViewTypes.ts#L229

**Comment by Titozzz** [comment]
@tmaly1980 Sorry I did not see your message
@jamonholmgren Thanks for clarifying

**Pull request closed without merging**
