### PR TITLE
Failed to load local html files in real devices

### PR DESCRIPTION
**Pull request by jimerino**

### CODE REVIEW

**Comment by jimerino** [comment]
This PR is related with

kCFErrorDomainCFNetwork (error code 1) in real device but no in simulator #396

**Comment by harrisrobin** [comment]
@jimerino, thanks for this PR!
Since you need a device to test this, I'd like to ask if you've had a chance to test it on an actual device yourself?

**Comment by jimerino** [comment]
@harrisrobin you're wellcome!

I've tested it in a real device before publish the PR in my fork and works. Do you have any pre-release branch to merge the PR and test or a test in my fork is enough?

**Comment by harrisrobin** [comment]
Ok, finally managed to test it on a real device. Looks good to me 👍 
@Titozzz LMK if we need anything else before we can merge this :)

**Comment by jamonholmgren** [comment]
Thanks for testing @harrisrobin !

**Comment by EstebanBP** [comment]
Is this PR published or merged into master?

**Pull request merged**
