### PR TITLE
[feat] Add `cacheEnabled` prop

### PR DESCRIPTION
**Pull request by Salakar**
This PR 'fixes' https://github.com/react-native-community/react-native-webview/issues/128 

cc @Titozzz @jamonholmgren as per linked issue above. Let me know your thoughts and if anything needs changing. I've enabled it by default as discussed with @Titozzz  on slack.

### Checklist

- [x] Android support
- [x] iOS support
- [x] Flow Types updated
- [x] Reference Documentation updated

### Release Notes

 - [BREAKING] [FEAT] Added a new ~`enableCache`~ `cacheEnabled` prop to toggle Android & iOS webview caching behavior. This change makes caching **enabled by default** when previously there was no caching behavior which may cause unexpected behaviour changes in your existing implementations.

### CODE REVIEW

**Comment by Salakar** [comment]
I need to do a few minor changes for Android still, please don't merge yet. Thanks

https://developer.android.com/reference/android/webkit/WebSettings.html#setAppCacheEnabled(boolean)
https://developer.android.com/reference/android/webkit/WebSettings.html#setAppCachePath(java.lang.String)
Both needed as well.

**Comment by Salakar** [comment]
Right, this should be good to go now, cc @Titozzz @jamonholmgren

**Comment by thedusty99** [comment]
Hey there! Thanks for your work! Is there anything stopping this PR from getting merged (besides the conflicts now)?

**Comment by Titozzz** [comment]
Yeah, it needs testing, because when I tested it I did not feel the expected improvements

**Comment by munsifhayat** [comment]
Any updates on this one ?
Need to have this 'WebCache' enabled property.

**Comment by Titozzz** [comment]
@munsifhayat did you test this PR works for you ?

**Comment by Titozzz** [comment]
Keep me updated

**Comment by jerolimov** [comment]
For my project I can confirm that this PR improves the caching and performance. 👍 

@Salakar @munsifhayat @Titozzz But unfortunately, in the `WebView.ios.js` its required to push the props to the `<NativeWebView...` in line 249 https://github.com/react-native-community/react-native-webview/blob/ac59610f55fbe909b2120dfef029ac4b33811b60/js/WebView.ios.js#L248-L258

Without this _enableCache is always false in `RNCWKWebView.m`. I expect that its similar on Android but doesn't debug it here.

I would also recommend to rename `enableCache` to `cacheEnabled` or `cachingEnabled` (or something similar), to match all the other [props](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#props-index)

But independently of this, this PR is great and important 👍

**Comment by Titozzz** [comment]
@jerolimov excellent catch about the props naming. We need to do that. 👍

**Comment by Titozzz** [comment]
@Salakar @jerolimov I updated the PR according to the reviews above :)
What do you think ?

**Comment by jamonholmgren** [comment]
Let's ship it!

**Comment by jerolimov** [comment]
@Titozzz Sorry for the delay. Thanks for applying the feedback. Sourcecode looks fine. I tested it also in a live project on iOS and it works as expected. 👍 

(I could not verify this yet on Android because I have other troubles here.)

**Comment by munsifhayat** [comment]
From my side I installed it got an RCTWebview error which I solved by dragging that library into Xcode project. 


Imported the Webivew as required and than : 
<WebView 
                ref="webview" 
                source={{ uri: this.state.url }} 
                onLoadEnd={e => this.webViewLoaded()}
                domStorageEnabled = {true}
                javaScriptEnabled = {true}
                style={styles.container}
                cacheEnable = {true}
           />

Rest are working fine but 'cacheEnable' could be verified once I have live build Soon. Let me know if anything need to change. 
I am using this for installing : 

"react-native-webview": "git+https://github.com/react-native-community/react-native-webview.git"

**Comment by munsifhayat** [comment]
Its working perfectly fine.

**Comment by NeverFearTheasHere** [comment]
I think this `cacheEnabled` prop is missing from the typescript prop type declarations (in`typings/index.d.ts`) so I've opened a PR for that: #335

**Pull request merged**
