### PR TITLE
fix(Android): Workaround for chromium bugs 1023678 and 1050635.

### PR DESCRIPTION
**Pull request by trcoffman**
# Summary
There is a bug in the WebView that causes a spurious call to onReceivedError
whenever you download a file.

This commit is a workaround for that bug. The idea here is to try and detect
these spurious errors and drop them before they cause problems.

This commit should be reverted once those chromium bugs are fixed.
https://bugs.chromium.org/p/chromium/issues/detail?id=1048335
https://bugs.chromium.org/p/chromium/issues/detail?id=1023678

This workaround addresses issue #1050 

## Test Plan

Download a file through the webview on an android device with an up-to-date chromium installed.

Here is a screenshot from our app:
Screen Shot 2020-02-19 at 4 51 22 PM

Without this fix, this happens when I click download:
Screen Shot 2020-02-19 at 4 50 26 PM

With this fix, the error doesn't happen.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator

### CODE REVIEW

**Comment by gregoryfm** [comment]
@jamonholmgren @Titozzz @safaiyeh 
Could you guys please review this PR?

Thanks.

**Comment by safaiyeh** [comment]
Approved @trcoffman

**Comment by gregoryfm** [comment]
Hi @safaiyeh, first of all, thanks for you time and work.

About this PR, what is missing to be merged? 
Can I do something to help?

Thanks

**Comment by safaiyeh** [comment]
Just need to merge master into it!

**Comment by gregoryfm** [comment]
Thank you @trcoffman

**Comment by trcoffman** [comment]
@safaiyeh I've merged master into the branch, can you please merge this?

**Comment by a4646054** [comment]
import WebView from 'react-native-webview';
exprot default class.........{
  render(){
return (<WebView source={require('./index.html')} ........./>)
}
.....}
Error:crypto.getRandomValues() not supported????????

**Comment by trcoffman** [comment]
> import WebView from 'react-native-webview';
> exprot default class.........{
> render(){
> return (<WebView source={require('./index.html')} ........./>)
> }
> .....}
> Error:crypto.getRandomValues() not supported????????why ?

That has nothing to do with this PR... or even this package in general. That's an error in your own codebase. React-native by default doesn't support crypto.getRandomValues(). You are gonna need this polyfill package for that: https://www.npmjs.com/package/react-native-get-random-values.

This isn't the appropriate place to talk about your issue though, this is a pull-request not an issue.

**Comment by humbertocruz** [comment]
on version 9.4.0 this problem is back ?

**Comment by schieck0** [comment]
> on version 9.4.0 this problem is back ?

Same problem here on this version

**Pull request merged**
