### PR TITLE
Add shared process pool so cookies and localStorage are shared across webviews in iOS

### PR DESCRIPTION
**Pull request by kylemantesso**
Add a shared process pool in iOS to allow shared cookies and localStorage between webviews. This brings iOS into line with expected behaviour in Android.

### CODE REVIEW

**Comment by lewnelson** [comment]
👏

**Comment by jamonholmgren** [comment]
So this is awesome and we actually need it on one of our projects at Infinite Red; thanks for the PR @kylemantesso !

A couple questions, though:

1. Given this will change current behavior and technically be a breaking change, should this be opt-in? Perhaps we should use a prop, like:

```js
<WebView
  source={{ uri: "https://infinite.red/react-native" }}
  sharedProcess={true}
/>
```

This could result in some pretty subtle bugs if someone was relying on the previous behavior.

At the very least, we should introduce as a breaking change but allow opting out with `sharedProcess={false}`.

2. Should we allow multiple (named) process pools?

I'd lean toward "no", but just putting it out there.

```js
<WebView
  source={{uri: "https://infinite.red/ignite"}}
  processPool="MAIN"
/>
```

We could then track each process pool in a dict in native code.

Again, this is probably not necessary, but just putting it out there.

Thanks again!

**Comment by kylemantesso** [comment]
Thanks @jamonholmgren! We also need this for a project, so keen to get it in!

I have refactored to make shared process pool optional, as per point 1 above. It will be a breaking change, but can be opted out by passing `useSharedProcessPool={false}` as a prop.

At this point we don't have a requirement for multiple process pools, but given the refactor this should make it easier to add later if it is required.

**Comment by felixmeziere** [comment]
Can we merge this?

**Comment by Titozzz** [comment]
@felixmeziere did you test this PR ?

**Comment by felixmeziere** [comment]
@Titozzz about to implement it on my project, is there a defined set of steps to test every feature?

**Comment by Titozzz** [comment]
Sadly not yet 😔 but we will need one

**Comment by kylemantesso** [comment]
Anything I can do to get this merged? What kind of testing do we need to perform?

**Comment by jamonholmgren** [comment]
@kylemantesso @felixmeziere  Apologies, I was out most of last week due to the holiday.

Have both of you tested this in your projects? If so, I'd say it's good to merge.

**Comment by Titozzz** [comment]
Hello, sorry about this, I've been working on a huge refactoring of the code, hopefully it will land soon, and I can get back to PRs. 😄

**Comment by kylemantesso** [comment]
@jamonholmgren Yes we are currently using it in our project for authentication cookie and local storage and it is working well.

**Comment by tigo0** [comment]
This works just fine in our project. Thanks!

**Comment by jamonholmgren** [comment]
@kylemantesso Can you resolve the conflicts? After that, I'd say we merge as breaking change. cc @Titozzz .

**Comment by kylemantesso** [comment]
@jamonholmgren @Titozzz have merged changes and have tested, confirmed working to share cookies/localStorage in iOS. Can we please merge this as a breaking change?

**Comment by stan-sack** [comment]
@kylemantesso does localStorage survive an app restart on iOS. I'm noticing that it's cleared every time I reload my app in Expo Go. Im not having much luck finding the behaviour documented anywhere

**Pull request merged**
