### PR TITLE
Proposal to add onOverrideUrlLoading for Android

### PR DESCRIPTION
**Pull request by maxammann**
This is only a proposal and we need to discuss how we implement this properly. **Maybe we also want to streamline this with iOS.**

Currently there is no way to block the navigation within an `WebView` completly and handle it on your own. E.g. to call `Linking.openUrl`.

This allows you to override all urls with `urlOverridingEnabled` and listen for events with `onOverrideUrlLoading`.

### CODE REVIEW

**Comment by maxammann** [comment]
@Titozzz I'm required to handle some links specially. For example I need to open a internal PDF viewer for PDF urls. I also need internal linking between screens of my navigator.

The OriginWhiteList is too limited for me because it always sends an intend.

**Comment by Titozzz** [comment]
Do you know if this is doable with the WKWebView for iOS?

**Comment by jamonholmgren** [comment]
@maxammann Thanks for submitting this proposal! One thing I'm not understanding is why doesn't `onShouldStartLoadWithRequest` work on Android?

**Comment by maxammann** [comment]
@jamonholmgren probably because it was simpler to implement on iOS. Or the original developer just didn't need the functionality.

**Comment by jamonholmgren** [comment]
Yeah, I'd agree with @Titozzz -- let's make the original API work properly! Would this break backwards compatibility? I don't imagine it would.

**Comment by maxammann** [comment]
Will come back to this PR soon. Could need some tips for easier development though. Currently I use Android Studio for the android/ project and IntelliJ for the JavaScript part.

How do you test a react-native library quickly on a device?

**Comment by GitHubTracey** [comment]
I can give you all the use case... In our web app we allow clients to edit certain data with html, but there may be several other fields on the form. When they are done, and we go to show it on mobile, I take that html and it stays in the same position in the page. Instead of opening it as a separate link, I use it inline. It works very well on ios... but android with the onShouldStartLoadWithRequest not working, it trys to open the links in the middle of my scrollview... not very effective for my use case !

**Comment by jamonholmgren** [comment]
@maxammann I'm hoping to make the development experience better in the coming months, including documentation about testing on device. Until then, just hack away best you can. :)

@GitHubTracey Good case study!

**Comment by maxammann** [comment]
So I looked yesterday into the day it works on iOS. The only way to use the return value of `onShouldStartLoadWithRequest` to cancel or continue with the loading is by cancelling it always and using `webview.loadUrl()` to navigate further.
(The reason is that the communication between native and react-native is async)

I'll test if this works properly on android or causes any glitches.

**Pull request closed without merging**
