### PR TITLE
Fix Android file upload

### LINKED ISSUE #876: No camera access in version 5
i was working with react-native-webview version 4 and all is fine : camera launched , video ... Now i upgraded to version 5 : when click on camera we don't get into camera : we get into file system . When i copy the  acceptsImages and acceptsVideo functions of version 4 in version 5 it works .
Can you explain to me please  why you added this extra code in acceptsImages and acceptsVideo in RNCWebViewModule.java ?

this is not working code
```
  private Boolean acceptsImages(String types) {
    String mimeType = types;
    if (types.matches("\\.\\w+")) {
      mimeType = getMimeTypeFromExtension(types.replace(".", ""));
    }
    return mimeType.isEmpty() || mimeType.toLowerCase().contains("image");
  }

  private Boolean acceptsImages(String[] types) {
    String[] mimeTypes = getAcceptedMimeType(types);
    return isArrayEmpty(mimeTypes) || arrayContainsString(mimeTypes, "image");
  }

  private Boolean acceptsVideo(String types) {
    String mimeType = types;
    if (types.matches("\\.\\w+")) {
      mimeType = getMimeTypeFromExtension(types.replace(".", ""));
    }
    return mimeType.isEmpty() || mimeType.toLowerCase().contains("video");
  }

  private Boolean acceptsVideo(String[] types) {
    String[] mimeTypes = getAcceptedMimeType(types);
    return isArrayEmpty(mimeTypes) || arrayContainsString(mimeTypes, "video");
  }
```
and this is working code of version 4 : 

  ```
private Boolean acceptsImages(String types) {
    return types.isEmpty() || types.toLowerCase().contains("image");
  }
  private Boolean acceptsImages(String[] types) {
    return isArrayEmpty(types) || arrayContainsString(types, "image");
  }

  private Boolean acceptsVideo(String types) {
    return types.isEmpty() || types.toLowerCase().contains("video");
  }
  private Boolean acceptsVideo(String[] types) {
    return isArrayEmpty(types) || arrayContainsString(types, "video");
  }
```

### LINKED ISSUE #1089: File Upload no camera selection
Hello everyone,

this issue was already asked but with no answer it was closed. On Android (no iOS for testing) I get no options to choose for camera/video/file. 

With the old code without the regexp matching it works fine. Sadly I'm pretty new to this area and cannot debug it, why this match triggers and what types are returned.

```
    if (types.matches("\\.\\w+")) {
      mimeType = getMimeTypeFromExtension(types.replace(".", ""));
    }
```

https://github.com/react-native-community/react-native-webview/issues/876

I tried various input field settings with no success.

Cheers
Hannes

### PR DESCRIPTION
**Pull request by hojason117**
# Summary

This PR fixes a few file upload issues on Android.
- #### Missing `Camera` and `Camcorder` options when input tag has no `accept` attribute. (fixes #876, fixes #1089 )
```html
<input type="file" >
```
##### Before and After
<p>

</p>

- #### Uploading multiple files results in only the first one being uploaded.
```html
<input type="file" multiple >
```
##### Before and After
<p>

</p>

- #### Incorrect image uploaded when input accepts both image and video.
```html
<input type="file" accept="image/*,video/*" >
```
##### Before and After
<p>

</p>

- **Redundant image/video filename during upload.**
Change filename from `image-1586291.jpg3661752427.jpg` to `image-3661752427.jpg`.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by hojason117** [comment]
@jamonholmgren @Titozzz @safaiyeh 
Could you guys take a look at this when you get a chance? Thx 🙏

**Comment by forward-S** [comment]
Hi @hojason117 
The changes are great. We have been getting the issues. We expect they will be released asap.
By the way, we got another issue.
It is that this package recoginzes very short video(1s~2s) into image.
Screenshot_81

How can we solve this?

**Comment by hojason117** [comment]
@forward-S Thanks for the comment! I think the issue you were seeing should be fixed by this PR.
Before this PR, both photo and video intent share the same placeholder file(where the photo/video is going to be written to) and that could cause many unexpected behaviors. This PR creates separate placeholder files for photo and video so this sort of confusion should go away.

**Comment by forward-S** [comment]
@hojason117 Thanks for your comment!
To give correct information, video length doesn't seem to matter.
We could upload correctly the video on Sumsung Galaxy C8(Android version 8.1.0), but couldn't do on Sumsung Galaxy S10+(Android version 10).

**Comment by hojason117** [comment]
@forward-S Which `react-native-webview` version are you using and what MIME type does your input tag accept? I don't have an Android 10 phone to test, but I did test this PR with an Android 10 emulator and it worked fine.

**Comment by forward-S** [comment]
@hojason117 we are using react-native-webview(8.0.6) and the input tag accepts these types "image/*,video/*".

**Comment by hojason117** [comment]
@forward-S Yeah it sounds like the bug I described in [this commit message](https://github.com/react-native-community/react-native-webview/pull/1302/commits/891aaaa4dd5c46e6f735723698f6a7c9c4fad81a), but the other way around. Hopefully we can get this merged soon and most likely this PR will solve that issue 🤞

**Comment by forward-S** [comment]
@hojason117 Yeah, We also want this PR to get released. Thanks.

**Comment by trcoffman** [comment]
@jamonholmgren, could you merge this PR or do you want someone else like @safaiyeh to merge it?

**Comment by jamonholmgren** [comment]
@trcoffman I can do it. Looking into the conflicts now.

**Comment by nyazidcap** [comment]
No for webview. Only for web.

**Pull request merged**
