### PR TITLE
Implement refresh control on Android and iOS

### LINKED ISSUE #103: Pull To Refresh feature in Webview
Is there any good way to support something like `refreshControl`? 
I saw one discussion regarding this - https://github.com/facebook/react-native/issues/7870

### PR DESCRIPTION
**Pull request by jerolimov**
Work in process... Update coming soon.

This will fix #103 (and facebook/react-native#7870)

Currently without any props to configure if the refresh control is available or not. And which color the refresh control has.

Will add this props later and submit this PR than. :)

### CODE REVIEW

**Comment by FlorisWarmenhoven** [comment]
Excellent! When you finalize this PR, please provide us with steps to reproduce the bug so that we can test it.

Looking forward to the finalized PR, @jerolimov.

**Comment by lashansam** [comment]
Any update on this?

**Comment by sinhpn92** [comment]
Waiting for this :D

**Comment by sinhpn92** [comment]
I have check it. But the callback do not work :(

**Comment by harutyundr** [comment]
I hope this will be merged soon.

**Comment by jerolimov** [comment]
After hard weeks of work and a long vacation I hope I will find the time soon to work again on this feature. If some company is interested into this feature for a coming soon launch, feel free to write me an email.

**Pull request closed without merging**
