### PR TITLE
Update Debugging.md

### PR DESCRIPTION
**Pull request by jamonholmgren**
The new debugging guide is great but the filename is wrong. Also added a screenshot. cc @ryanlntn

### CODE REVIEW

**Comment by Titozzz** [comment]
@jamonholmgren Are you sure the screenshot really has value? Maybe it would be better to show how to access remote devices

**Comment by jamonholmgren** [comment]
@Titozzz I find it's helpful to give people a preview of what they can expect when they do this. I can make it smaller if it's too overpowering?

**Comment by Titozzz** [comment]
Maybe it's too big... also we could add smaller screenshots of every steps in addition too 😄 ?

**Comment by Titozzz** [comment]
We need to merge this to fix the docs, we will iterate on it later

**Pull request merged**
