### PR TITLE
add raw compability with react-native-windows

### PR DESCRIPTION
**Pull request by mroswald**
Libraries like [react-native-canvas](https://github.com/iddan/react-native-canvas) rely on `react-native-webview` to export the `WebView`. Unfortunalty for `react-native-windows` this won't work as an internal import can't be resolved.

This PR resolves the WebView to the original WebView provided with `react-native-windows` in order to give _some_ compability which seem better to me than _no_ compability :)

I saw this comment in the contribution guide: `If you want to add another React Native platform to this repository, you will need to create another .flowconfig for it.` Although I value testing things, I don't think it makes much sense to cover a pure export/import.

### CODE REVIEW

**Comment by sjchmiela** [comment]
🤔 Removing `.windows` part would also fix basic compatibility (compile-time) with `react-native-web` 🙃

**Comment by Titozzz** [comment]
@sjchmiela that's smart. Might do it 😁

**Comment by mroswald** [comment]
Yes, on the other hand I wanted to avoid problems with platforms that are not yet covered and do not have `WebView` exported. This in mind, would you also suggest to remove the file suffix?

**Comment by Titozzz** [comment]
Well importing something that does not exist should not crash, it would just be null right?

**Comment by mroswald** [comment]
You're right. Will adjust this PR.

**Comment by Titozzz** [comment]
Because of the TS rewrite, I directly included this in my PR so you don't fight against merge conflicts

**Pull request closed without merging**
