### PR TITLE
add targetFrame to nativeEvent on onShouldStartLoadWithRequest

### PR DESCRIPTION
**Pull request by francisco-sanchez-molina**
On my app I have a custom logic to open some external links in the mobile browser. But I have too an iframe with some links that can modify the url of these iframe. For this reason I need to differentiate if the change of url is in the main frame or in another to apply my custom logic.

PD: In android onNavigationStateChange is not fired with iframe links

### CODE REVIEW

**Comment by Titozzz** [comment]
We try to keep the events consistent between Android and iOS , is the same feature doable on Android ?

**Comment by jerolimov** [comment]
On Android (since Android >= 7.0, API level 24) this is also supported on Android. See:

https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest)

**Comment by francisco-sanchez-molina** [comment]
`onShouldStartLoadWithRequest` callback is only available on ios. 

image

For this reason the event "is consistent". But, I think that another PR can implement this callback for android and send url, navigationType and targetFrame data.

What do you think?

**Comment by Titozzz** [comment]
Sorry there is already a PR which is why I'm mistaken. It's a bit stuck tho, so please come and discuss #106

**Comment by Titozzz** [comment]
@francisco-sanchez-molina Now that the feature also exist on android, I'd like to stay consistent and implement it on both places at once

**Comment by francisco-sanchez-molina** [comment]
Hi @Titozzz, I am going to review it as soon as possible, and I will tell you if I can do it ;)

**Comment by Titozzz** [comment]
Thank you so much for the instant reply ❤️

**Comment by vivan-niche** [comment]
since the android API just returns a boolean, it may make sense to return a boolean `isMainFrame` instead of the main frame name or `other` ?

**Comment by jamonholmgren** [comment]
I'm okay with this change, even if it's iOS-only. However, let's make sure that documentation is updated too. See PR https://github.com/react-native-community/react-native-webview/pull/493 for an example of how to do this.

**Pull request closed without merging**
