### PR TITLE
Add a .gitattributes to fix line endings across myriad files.

### PR DESCRIPTION
**Pull request by trcoffman**
# Summary

The repository is now receiving contributions from windows users, which means we need a .gitattributes set up to keep all the line endings from being converted to CRLF whenever they get touched by a windows dev.

I just experienced bogus merge conflicts in package.json and yarn.lock when rebasing an old branch. Because the line endings had been trashed due to carelessness, the entire file showed up as one huge merge conflict.

### CODE REVIEW

**Comment by trcoffman** [comment]
@safaiyeh @jamonholmgren Could we get this one merged quickly? This should get merged before any other PRs get merged so that we can get the line endings back under control before more files get affected.

**Comment by trcoffman** [comment]
https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Comment by jamonholmgren** [comment]
@trcoffman Very sorry, didn't see this until now. Can you fix conflicts (or re-submit the PR) and then ping me in [Twitter DMs](https://twitter.com/jamonholmgren) and tag me here so I can merge it quickly?

**Comment by trcoffman** [comment]
@jamonholmgren I just rebased on master and re-ran the renormalization.

**Comment by jamonholmgren** [comment]
Thank you @trcoffman !

**Pull request merged**
