### PR TITLE
feat(library): Rename module to @react-native-community/webview

### PR DESCRIPTION
**Pull request by safaiyeh**
# Summary
Promote consistent module names across the react-native-community. This renames the module to `@react-native-community/webview`

### What's required for testing (prerequisites)?
Test that the module still works as expected under the new module name.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by sebinq** [comment]
@safaiyeh I think that this is very good idea. Is there any proposal for react-native-community packages to remove every redundant 'react-native' for all the community packages?

**Comment by safaiyeh** [comment]
@sebinq No official proposal, something that has been discussed internally in the community.

Many packages already do it: cli, async-storage, cookies,.. etc

**Comment by jamonholmgren** [comment]
Would we continue to publish to `react-native-webview` on NPM as well?

**Comment by safaiyeh** [comment]
@jamonholmgren I am assuming `@react-native-community/webview`

**Pull request closed without merging**
