### PR TITLE
feat(WKWebView): [ios] RNCWKWebView send headers on all page requests

### LINKED ISSUE #4: MIGRATED: WebView does not send custom request header after the first initial page load (#8693)
Migrated from React Native core: https://github.com/facebook/react-native/issues/8693

@chiraggshah says:

---

The source prop for WebView allows for passing request headers. When the webview renders for the first time, the request headers are sent.

But when the links within that page are clicked, the headers are not sent to the server in the request header.
Similarly, when the goBack() method is called on the WebView, the request headers are not being sent.

---

_More context available in the original issue._

### PR DESCRIPTION
**Pull request by mattycas**
This enables the WKWebView implementation to send the headers set on the `source` prop on every page load request rather than just the initial load request.

Fixes #4, #68, and #25

### CODE REVIEW

**Comment by Titozzz** [comment]
Hello, thank you for this, I've seen it requested a lot, could the same be done for android ?

**Comment by mattycas** [comment]
Hey @Titozzz thanks for your quick reply. It was my understanding that android would send through the headers for all GET requests. Is that not right?

Understandably this is a fairly controversial change/implementation and a breaking one as well. Should I add a prop to RNCWKWebView to enable this behaviour?

**Comment by Titozzz** [comment]
If you just align iOS functionality to android, it might be a bugfix. If we change behavior, we can do breaking change easily with semver anyway so don't worry too much about it.

**Comment by jamonholmgren** [comment]
Note that Android does _not_ set headers on subsequent page loads. This will need to be done for Android as well.

@Titozzz Do you want to require that we do this for Android before merging or are you okay merging with iOS only?

Secondly, do we want to add a feature flag? I think it's fine to publish without a flag, but it is a breaking change.

**Comment by Titozzz** [comment]
If there is a way to have this on android at the same time it would be awesome, as the difference between the two would be quite annoying I think ?

If we do both at the same time I don't think feature flag is necessary, but if it's only on iOS it would prob be better

**Comment by ralesiupgrade** [comment]
Hey hows it going? I been following along in the chain of PRs and issues and was having an issue in iOS similar to https://github.com/react-native-community/react-native-webview/issues/68 and it looks like this will fix it. Any progress on getting this merged :) My android build works fine but looks like for now for iOS i will have to use `useWebKit={false}` until this is merged. Thanks

**Comment by smathson** [comment]
I'd like to argue for this being opt-in behavior and not the default. Any site that uses Authentication headers and also whitelists third-party domains for valid reasons (think youtube embeds) would be unintentionally leaking authentication tokens by default without a clear way to opt-out unless I'm missing something.

Also since the prop that gets passed is a `source` object with `uri` and `headers`, it seems a bit unclear that the headers would also be implicitly sent along to potentially different hosts. Moving the behavior to an optional prop of headers that get merged into every request (i.e. `defaultHeaders`) and then noting the potential security risks might be a more "secure-by-default" and flexible approach. 

This way someone could attach authentication headers to specific requests by changing the `source` prop and still provide a list of default headers that are fine to send with every request OR go ahead and add authentication headers to the `defaultHeaders` and only whitelist trusted domains.

**Comment by mattycas** [comment]
I agree @smathson . If @Titozzz and @jamonholmgren agree I am happy to put this behind a feature flag prop.
I could also limit it to only user initiated actions on the same host as the source request's host?

**Comment by Titozzz** [comment]
What would be the best way to achieve something that would work for everyone ?

Setting headers on a host basis ? on a request basis ? Apparently not the same header for all requests 😛 .

**Comment by smathson** [comment]
@mattycas That sounds like it makes sense to me as long as the headers are only sent along to the original host. I guess it would be possible for someone to update just the `uri` on the `source` prop object and forget about `headers` still being set, but that seems like an edge case to me. Maybe we could add a note to the docs to be careful to set the entire `source` prop when using authentication headers to avoid leaking tokens.

**Comment by smathson** [comment]
@jamonholmgren I like that. Makes it explicit and makes people think about which headers they are attaching for which requests.

**Comment by mattycas** [comment]
@jamonholmgren this is a nice solution and I'm happy to update the PR.

**Comment by Titozzz** [comment]
Is there a way to achieve the same behavior on android?

**Comment by jamonholmgren** [comment]
On Android, it looks like we can set custom headers by overriding `shouldInterceptRequest` (see [here](https://developer.android.com/reference/android/webkit/WebViewClient.html#shouldInterceptRequest) and the [Stackoverflow answer](https://stackoverflow.com/a/29811280/204044) I saw first). 

We should probably make the behavior the same across iOS and Android.

**Comment by chiraggshah** [comment]
@mattycas : It would be nice to know the reason why this was closed, since this had active discussion around it? Was there a separate PR which caused this to be closed?

**Comment by jamonholmgren** [comment]
I'd love someone to champion this PR and move it forward. Any volunteers?

**Pull request closed without merging**
