### PR TITLE
fix(Android): WebRTC permission request (#231)

### PR DESCRIPTION
**Pull request by Javascript-Ninja**

### CODE REVIEW

**Comment by Titozzz** [comment]
Pleas read https://developer.android.com/reference/android/webkit/PermissionRequest

And update your code above to match android guidelines

**Comment by Titozzz** [comment]
@Javascript-Ninja up ?

**Comment by Javascript-Ninja** [comment]
@Titozzz Maybe we can callback to js? Or checkSelfPermission and requestPermissions?

**Comment by Titozzz** [comment]
What I meant was about that part :
```
To avoid unintentionally granting requests for new permissions, you should pass the specific permissions you intend to grant to grant(), and avoid writing code like this example:

 permissionRequest.grant(permissionRequest.getResources())  // This is wrong!!!
 
```

**Comment by Javascript-Ninja** [comment]
@Titozzz Updated.

**Comment by ralesiupgrade** [comment]
Hey i was seeing the same issue in iOS, I wonder if this is related?

**Comment by ASteinheiser** [comment]
Any updates on this getting to master? I just tested the branch on my project and it allowed me to get permissions for my webcam in the WebView.

**Comment by Titozzz** [comment]
It should land eventually when I have time! Don't worry 😛😊

**Comment by ASteinheiser** [comment]
Quick note after testing this branch:
It seemed to work at first. However, after closing the app and re-opening, the page with the webcam just fails silently.
Before I used this fork, it was at least giving me an error: "Permission not granted" or something.

**Comment by hanqingqingmomo** [comment]
@Javascript-Ninja   it's also show the NotAllowedError error？

**Comment by mdabees** [comment]
> It should land eventually when I have time! Don't worry 😛😊

Hello can we get this to the master branch asap, this is a major issue when using web-view for anyone who needs to upload photos directly from camera roll.

**Comment by Titozzz** [comment]
Hello @mdabees, @ASteinheiser said there was some issues and no one ever clarified if it was indeed working, this is why this is not merged yet. Can you try to reproduce to see if there is indeed a problem?

**Comment by hanqingqingmomo** [comment]
@Javascript-Ninja hello, can you fix these conflicts?

**Comment by hanqingqingmomo** [comment]
@Javascript-Ninja hello, can you fix these conflicts when you have time?

**Comment by Titozzz** [comment]
@hanqingqingmomo Feel free to iterate over his work and submit a PR with the needed fixes

**Comment by hartatovich** [comment]
+1

**Comment by Javascript-Ninja** [comment]
#719

**Pull request closed without merging**
