### PR TITLE
fix: add `Referer` header for Android `loadUrl()` command

### PR DESCRIPTION
**Pull request by rocwind**
- add "Referer" header in Android `loadUrl()` command to fix issues that caused by its absense
- expose `referer` field to `onShouldStartLoadWithRequest` event to let client include it into custom headers when necessary

# Summary
This is an update of previous PR #1200 

For redirected url loading, current behehavior is we always return true to prevent it being loaded in shouldOverrideUrlLoading, with TopShouldStartLoadWithRequestEvent being sent to RN and then call webview.loadUrl() if such redirect loading was approved on RN.
However, the Referer header would be different between webview.loadUrl and return false in shouldOverrideUrlLoading. It might cause redirect issues ( #1073, #1434 ) 

The proposed solution here is to:
1. (Android) keep a referer url when navigation happens and use it as referer header as default behavior.
2. (Both Android & iOS) include the `referer` along with other parameters in `onShouldStartLoadWithRequest` to let js land have a chance to deal with combining referer and other custom headers

Regarding the multiple consecutive redirects case described in #1434 (details: https://github.com/react-native-community/react-native-webview/pull/1200#issuecomment-650983886). It may still have issue on Android 6.0 and below with this fix. Since `boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request)` only works on Android N and above, and we cannot tell if current url loading request is server redirect or not without the `WebResourceRequest` - cannot decide whether the referer header need to be updated or not.

## Test Plan
1. test loading https://s.click.taobao.com/fj2tptv (url from #1073 )
2. test loading https://mijn.uwv.nl/ and click the leftmost button labeled 'DigiD Inloggen' ( #1434) on Android 7+

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by jamonholmgren** [comment]
This looks good. Can someone test it to make sure it works?

**Comment by felipeaugusto1** [comment]
I just tested on an Android device and confirm that it works

**Comment by Transfusion** [comment]
Tested in the Pixel 2 API 29 simulator, my use case is a website that only allows downloading of certain files if the referrer is on the same domain, and returns a 403 page otherwise. With the changes above the file download was triggered by the DownloadManager, which is an improvement over the behavior in master (the WebView redirects to the 403 page directly), however, because the DownloadManager didn't pass the Referer on, the resulting file's contents were the HTML plaintext of the 403 page.

I suggest adding 
```java
        String refererUrl = ((RNCWebView) webView).progressChangedFilter.getRefererUrl();
        if (refererUrl != null &&
          // "no-referrer-when-downgrade" policy is the default behavior
          // https://www.w3.org/TR/referrer-policy/#referrer-policy-no-referrer-when-downgrade
          (!refererUrl.startsWith("https://") || url.startsWith("https://"))
        ) {
          request.addRequestHeader("referer", refererUrl);
        }
```
right below https://github.com/react-native-community/react-native-webview/blob/261ba6c60d1a3d4101c48c198e59744ae7a29814/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L223 
to ensure that the Referer is passed over to the `DownloadManager` too.

**Comment by rocwind** [comment]
Thanks for the testing & great suggestions.

I saw #1590 has been merged and released in v10.8.3: by handling the `shouldOverrideUrlLoading` in synchronous way and rely on the system (webview) default behavior, the redirect issue this PR was targeting for should be solved in #1590 too. So I am closing this PR as it seems no longer needed.

**Comment by timboektoe** [comment]
We also tested this PR for mijn.uwv.nl and problem is solved now. Great work!

**Pull request closed without merging**
