### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by doomsower**
Typescript definitions are based on flow
Tested them a bit in my project
I think couple of event types are screwed in flow definitions (synthetic/non-synthetic are mixed), tried my best to test which events are really received.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Awesome @doomsower ! Thanks for doing this.

Is there a way to automatically generate updated typings when we update the Flow types?

**Comment by doomsower** [comment]
> Is there a way to automatically generate updated typings when we update the Flow types?

There are some projects, I haven't tried any of them myself. And it looks like none of them is mature enough to work without further human post-processing.

**Comment by Titozzz** [comment]
That is cool 🔥. 

Makes me think that since most of the devs use VScode anyway I have the feeling it would make sense to replace flow with TS ? What do you guys think. I felt like using flow was kinda painful

**Pull request merged**
