### PR TITLE
Fix compilation by renaming a class usage

### PR DESCRIPTION
**Pull request by maxammann**
This is not usable currently because it does not compile for android. I need this because of this issue right now: https://github.com/facebook/react-native/issues/21104

Compiling for mac still does not work.

### CODE REVIEW

**Comment by Titozzz** [comment]
Ouch you are right 100% can you remove the whitespace diff please and i'll merge it

**Comment by maxammann** [comment]
@Titozzz oh yeah, sure. Will do a proper PR now :P 
Can you maybe take a look at the ios code? Not experienced with objective-c :)

I get this error:
```
/RCTUIWebViewManager.m -o /Users/integreat/integreat-react-native-app/ios/build/Build/Intermediates.noindex/RCTWebView.build/Debug-iphonesimulator/RCTWebView.build/Objects-normal/x86_64/RCTUIWebViewManager.o

/Users/integreat/integreat-react-native-app/node_modules/react-native-webview/ios/RCTUIWebViewManager.m:64:7: error: multiple methods named 'goForward' found with mismatched result, parameter type or attributes
      [view goForward];
      ^~~~~~~~~~~~~~~~
In module 'UIKit' imported from /Users/integreat/integreat-react-native-app/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTViewManager.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIWebView.h:56:1: note: one possibility
- (void)goForward;
^~~~~~~~~~~~~~~~~~
In module 'WebKit' imported from /Users/integreat/integreat-react-native-app/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:18:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebView.h:200:1: note: also found
- (nullable WKNavigation *)goForward;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/integreat/integreat-react-native-app/node_modules/react-native-webview/ios/RCTUIWebViewManager.m:6:
/Users/integreat/integreat-react-native-app/node_modules/react-native-webview/ios/RCTUIWebView.h:32:1: note: also found
- (void)goForward;
^~~~~~~~~~~~~~~~~~
1 error generated.



** BUILD FAILED **
```

**Comment by Titozzz** [comment]
Theses are 2 separate issues, can you please open a new issue (with RN version, and package.json) and I'll investigate. This error happened to me before when I had many react-native-webview libraries in only one project.

**Comment by Titozzz** [comment]
ty vm 🎉

**Comment by jamonholmgren** [comment]
@maxammann Thanks so much!

**Comment by maxammann** [comment]
@jamonholmgren No problem :) This package is the only way to use the webview with local files atm because this commit is missing in RN 0.57.0 https://github.com/facebook/react-native/commit/0c576ef84a1c7f79b228f205cc687ab1b945bda1

**Comment by jamonholmgren** [comment]
@maxammann That's good to know. I've passed it along to the core team.

**Comment by maxammann** [comment]
@jamonholmgren cool thank you ;)

**Pull request merged**
