### PR TITLE
Fix recreate bug

### PR DESCRIPTION
**Pull request by NeilChan**
refer to [https://github.com/react-native-community/react-native-webview/issues/81#issue-370428707](url)

I think it just missing a judgement. Place it on 'didMoveToWindow' should be good for the performance.

### CODE REVIEW

**Comment by Titozzz** [comment]
@finalquest @viv3kk @fangasvsass @garrettm Can you guys test that PR and confirm it's working fine :) ?

**Comment by garrettm** [comment]
From a quick test, appears to fix the problem

**Comment by garrettm** [comment]
Any ETA for when this might get merged and a new release pushed?  Trying to figure out if I need to fork this repo or if I can wait for the fix here.

**Comment by fangasvsass** [comment]
works fine for me

**Comment by Titozzz** [comment]
Perfect. With the work I did yesterday I can release from my phone 😍

**Comment by Titozzz** [comment]
Perfect. With the work I did yesterday I can release from my phone 😍

**Comment by malonguwa** [comment]
@Titozzz How should I prevent the webView being re-create but also still able to have the onMessage event? I do not quite familiar with WKWebView, please advice, without fix, this is a quite important bug for the WKWebView component.

**Comment by NeilChan** [comment]
@malonguwa Thanks. It is my fault. 
‘ removeScriptMessageHandlerForName:MessageHanderName’ if not called, it maybe cause memory leak.  Call in 'dealloc' method can't solve this problem. 
It affect 'ReactNative' messageHandler, so the method in javascript 'window.postMessage()' maybe not evaluate on right way.

So you can delete this code temp
`else {
    [_webView.configuration.userContentController removeScriptMessageHandlerForName:MessageHanderName];
  }`

and override 'removeFromSuperview' method 
`
- (void)removeFromSuperview{
    [super removeFromSuperview];
    if (_webview) {
       [_webView.configuration.userContentController removeScriptMessageHandlerForName:MessageHanderName];
       _webview = nil;
    }
}
`

I will test it and submit a PR.

**Comment by Titozzz** [comment]
Hello guys, please keep me updated on this.

**Comment by NeilChan** [comment]
@malonguwa Good.

**Comment by Titozzz** [comment]
Any update ?

**Comment by NeilChan** [comment]
@Titozzz Have submitted a PR.

**Pull request merged**
